version: '3'
services:
  nginx:
    image: nginx:1.19
    container_name: nginx
    volumes:
      - "${PWD}/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    networks:
      - grafana-influx
    ports:
      - "${NGINX_EXT_PORT}:80"
    restart: always
    env_file:
      - .env
  influxdb:
    image: influxdb:1.7
    container_name: influxdb
    volumes:
      - influxdb_data:/var/lib/influxdb
      - "${PWD}/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro"
    networks:
      - grafana-influx
    ports:
      - "${INFLUXDB_EXT_PORT}:8086"
    restart: always
    env_file:
      - .env
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - "${PWD}/grafana/defaults.ini:/usr/share/grafana/conf/defaults.ini:ro"
      - "${PWD}/grafana/etc/grafana/provisioning:/etc/grafana/provisioning"
      - "${PWD}/grafana/log:/var/log/grafana"
    networks:
      - grafana-influx
    ports:
      - "${GRAFANA_EXT_PORT}:3000"
    restart: always
    env_file:
      - .env

volumes:
  influxdb_data:
  grafana_data:

networks:
  grafana-influx:

